jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: CmdLine@2
    inputs:
      script: |
        sudo apt-get update
        sudo apt-get install castxml
  
  - script: |
      dotnet --info
      printenv
      ./build.sh --target "Azure-Linux" --configuration "Release"
     
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - task: Xcode@5
    inputs:
      actions: 'build'
      scheme: ''
      sdk: 'macosx10.13'
      configuration: 'Release'
      xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
      xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
      args: '-derivedDataPath ./' 
  - task: CmdLine@2
    inputs:
      script: brew install castxml

  - script: |
      dotnet --info
      printenv 
      ./build.sh --target "Azure-OSX" --configuration "Release"

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: PowerShell@2
    inputs:
      filePath: build.ps1
      arguments: -target "Azure-Windows" -configuration "Release"
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/artifacts/nuget'
      artifactName: 'NuGet'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/artifacts/zip'
      artifactName: 'Samples'
