jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      dotnet --info
      ./build.sh --target "Azure-Linux" --configuration "Release"
     
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - script: |
      dotnet --info
      ./build.sh --target "Azure-OSX" --configuration "Release"

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: PowerShell@2
    inputs:
      filePath: build.ps1
      arguments: -target "Azure-Windows" -configuration "Release"
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/artifacts/nuget'
      artifactName: 'NuGet'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/artifacts/zip'
      artifactName: 'Samples'
