jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      dotnet --info
      ./build.sh --target "Azure-Linux" --configuration "Release"
     
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - script: |
      dotnet --info
      ./build.sh --target "Azure-OSX" --configuration "Release"

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: .\build.ps1 --target "Azure-Linux" --configuration "Release"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: artifacts/